# Generated by Django 5.1.3 on 2024-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_swiper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_intro', models.TextField()),
                ('model_description', models.TextField()),
                ('model_image', models.URLField()),
            ],
        ),
    ]
