# Generated by Django 5.1.3 on 2024-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='model_description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='model_image',
            field=models.JSONField(),
        ),
    ]
