# Generated by Django 5.1.3 on 2024-12-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_detailpage_model_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailpage',
            old_name='model_description',
            new_name='model_info',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='model_image',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='model_intro',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='model_name',
        ),
    ]
